# Project information
site_name: Swift for Android
site_url: https://docs.swifdroid.com
site_author: Mikhail Isaev
site_description: SwifDroid documentation (Android framework for Swift).

# Repository
repo_url: https://github.com/swifdroid/droid
repo_name: swifdroid/droid
edit_uri: https://github.com/swifdroid/docs/edit/master/docs/

# Copyright
copyright: "SwifDroid Docs &copy; 2025 by Mikhail Isaev<br>Licensed under CC BY-NC-SA 4.0"
theme:
  name: material
  font: false
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.path
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.select
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: black
    accent: green

# Customization
extra:
  # Font
  font:
    text: Roboto Slab
    code: Source Code Pro
  # Social
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/+t9zXkfjoKNNlY2Ri
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/Wh3n86ttRB
    - icon: fontawesome/brands/github
      link: https://github.com/swifdroid
  # GDPR
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - assets/css/prism.css
  - assets/css/fonts.css

extra_javascript:
  - assets/js/prism.js
