# Project information
site_name: Swift for Android
site_url: https://docs.swifdroid.com
site_author: Mikhail Isaev
site_description: SwifDroid documentation (Android framework for Swift).

# Repository
repo_url: https://github.com/swifdroid/droid
repo_name: swifdroid/droid
edit_uri: https://github.com/swifdroid/docs/edit/master/docs/

# Copyright
copyright: "SwifDroid Docs &copy; 2025 by Mikhail Isaev<br>Licensed under CC BY-NC-SA 4.0"

theme:
  name: material
  custom_dir: theme/
  language: en
  font: false
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.path
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.select
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: black
    accent: green

# Customization
extra:
  # Analytics
  analytics:
    provider: google
    property: GTM-KKVJQPKW
  # Font
  font:
    text: Roboto Slab
    code: Source Code Pro
  # Social
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/+t9zXkfjoKNNlY2Ri
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/Wh3n86ttRB
    - icon: fontawesome/brands/github
      link: https://github.com/swifdroid
  # GDPR
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.

extra_css:
  - assets/css/prism.css
  - assets/css/fonts.css

extra_javascript:
  - assets/js/prism.js

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: false

nav:
  - Welcome: index.md
  - Setup:
    - setup/index.md
    - on macOS: setup/macos.md
    - on Linux: setup/linux.md
    - on Windows: setup/windows.md
  - Application:
    - app/index.md
    - Getting Started: app/getting-started.md
    - Structure: app/structure.md
    - Entry Point: app/entry-point.md
    - Logging: app/logging.md
    - Manifest: app/manifest.md
    - Activities: app/activities.md
    - Views: app/views.md
    - Assets: app/assets.md
    - R: app/r.md
    - Colors: app/colors.md
    - Themes: app/themes.md
    - ForEach: app/for-each.md
    - State: app/state.md
    - Units: app/units.md
    - Classic:
      - Lists and Collections:
        - HSpace: app/classic/h-space.md
        - HStack: app/classic/h-stack.md
        - Space: app/classic/space.md
        - VSpace: app/classic/v-space.md
        - VStack: app/classic/v-stack.md
    - Android X:
      - RecyclerView: app/x/recycler-view.md
    - Permissions: app/permissions.md
    - Shared Preferences: app/shared-preferences.md
  - Library:
    - lib/index.md
    - Getting Started: lib/getting-started.md
    - Structure: lib/structure.md
    - Swift Project: lib/swift-project.md
    - Kotlin Project: lib/kotlin-project.md
    - Code:
      - Development Loop: lib/code/development-loop.md
      - Entry Point: lib/code/entry-point.md
      - Class Loader: lib/code/class-loader.md
      - Logging: lib/code/logging.md
      - Sending an Int: lib/code/examples/sending-int.md
      - Sending an Int Array: lib/code/examples/sending-int-array.md
      - Sending a String: lib/code/examples/sending-string.md
      - Sending a Date: lib/code/examples/sending-date.md
      - Receiving a String: lib/code/examples/receiving-string.md
      - Wrapping a Class: lib/code/examples/wrapping-class.md
      - Async/Await: lib/code/examples/async-await.md
    - Distribution:
      - Library Import: lib/distribution/library-import.md
      - Standalone AAR: lib/distribution/standalone-aar.md
      - JitPack Repository: lib/distribution/jitpack.md
  - JNIKit:
    - jni-kit/index.md
    - Basics: jni-kit/basics.md
    - Initialization: jni-kit/initialization.md
    - Cache: jni-kit/cache.md
    - Types: jni-kit/types.md
    - Values: jni-kit/values.md
    - Classes: jni-kit/classes.md
    - Environment: jni-kit/env.md
    - Signature: jni-kit/signature.md
    - Objects: jni-kit/objects.md
    - Methods: jni-kit/methods.md
    - Fields: jni-kit/fields.md
    - Casting: jni-kit/casting.md
    - To String: jni-kit/to-string.md
    - Optionals: jni-kit/optionals.md
    - Examples: jni-kit/examples.md
  - Contributing: contributing.md
